### PR TITLE
Feature/milestone1 for Review

### PR DESCRIPTION
**Pull request by trox115**
- Set up Linters
- App deployed to Heroku
- ReadMe updated
- Link to heroku [here](https://antonioreact-bookstore.herokuapp.com/) if you do not want to search the readme.
### TSE : 
I know that this is not a solo project, however I did not have a partner (available) so me and Willow have decided that it was better for me not to wait since there was only one project left.

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @trox115 
great job,
plase remove unecessary files :
-App.test.js	
- index.css	
- logo.svg	
- serviceWorker.js	
- setupTests.js
- App.css

And file for last review
Happy coding

**Comment by trox115** [comment]
Just let that there because I find that React page beautiful :smirk: 

Will do that

**Review by shloch — COMMENTED** [review]
Hello @trox115 
Nice......You can merge😊

**Review by shloch — APPROVED** [review]
See you on next milestone 😊😊😊😊😊

**Pull request merged**
